version: "3"


services:
  web:
    image: 'pmt'
    build:
      context: .
      dockerfile: ./dockerContainer/Dockerfile
    restart: always
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
