version: "3"


services:

  graphql: 
    image: 'hasura/graphql-engine:v1.3.2'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://ad:pass@database:5432/pmt
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
    ports:
      - 8090:8080


networks:
  default:
    external:
      name: pmt_network
