version: "3"


services:

  database: # https://hub.docker.com/_/postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ad
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pmt
      # PGDATA: # define location of datafiles, default: /var/lib/postgresql/data
    ports:
      - 5432:5432

    # stdin_open: true
    # tty: true


networks:
  default:
    external:
      name: pmt_network